### ISSUE TITLE
post-release polishing

### ISSUE THREAD

**Issue by kiniry** [GaloisInc/HARDENS#135]
- [x] cleanup duplicate generated PDFs from Markdown and LaTeX (e.g., `HARDENS_Oct_2022.pdf`)
- [x] add copyright notice to FRET specifications
- [x] double-check copyright attributions for Bluespec vs. Nikhil
- [x] ensure License sections in Markdown documents look right natively and after Pandoc processing
- [x] embellish the header on every C file to document the file's purpose and use
- [ ] ~~update SysML in report~~ see #142 instead
- [x] `develop` and `main` diverged, some commits were merged to `main` but not to `develop` - this needs to be cleaned up (maybe just stick to `develop` and remove `main`?)
- [x] decide which docker image we support (there is one in artifactory that is internal, but we also have somehow one image on [DockerHub](https://hub.docker.com/r/galoisinc/hardens)) - and update docs and scripts accordingly
- [x] Update proposal language (remove "Confidential" note from the proposal PDF) [link](https://github.com/GaloisInc/HARDENS/commit/1379c1e042ebfe7447d5e42887ec54e91c730d3a)

**Comment by kiniry** [comment]
I've asked Nikhil for input on subtask 3 above.

**Comment by rsnikhil** [comment]
Have responded to @kiniry by email.  All ok.

**Comment by kiniry** [comment]
There is no need to update the graphical SysML in the report, as we had removed, at least for the moment, any inclusion of graphical elements.  The textual specification does need to be updated.

**Comment by kiniry** [comment]
I'm waiting to hear back from @SimplisticCode about the workflow for updating the final report using the RDE_RF tool.
